image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - unittest
    - integrationtest

variables:
    srcDir: "src"
    projectName: "FluiTec.AppFx.Data"
    testfilter: "FullyQualifiedName~FluiTec.AppFx.Data&FullyQualifiedName~-Tests"
    integrationfilter: "FullyQualifiedName~FluiTec.AppFx.Data&FullyQualifiedName~-IntegrationTests"
    GIT_SUBMODULE_STRATEGY: recursive
    
before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - "cd $srcDir"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build --no-restore"
        
unittest:
    stage: unittest
    script:
        - dotnet test --no-restore --filter $testfilter

integrationtest:
    stage: integrationtest
    script:
        - dotnet test --no-restore --filter $integrationfilter