name: build

on: [push]

env:
  TEST_FILTER: "FullyQualifiedName~FluiTec.AppFx.Data&FullyQualifiedName~.Tests"
  INTEGRATION_FILTER: "FullyQualifiedName~FluiTec.AppFx.Data&FullyQualifiedName~.IntegrationTests"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v3
      with:	
        submodules: true
    - name: setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: restore
      run: dotnet restore
    - name: build
      run: dotnet build --no-restore
    - name: unit test
      id: test
      run: dotnet test --no-build --verbosity normal --filter $env:TEST_FILTER
    - name: integration test
      if: (steps.test.conclusion == 'success')
      run: dotnet test --no-build --verbosity normal --filter $env:INTEGRATION_FILTER
